packages:
  - "."

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true

overrides:
  oxc-parser: 0.140.0

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - unrs-resolver
  - vue-demi
